-- MENufy - instalação completa

-- MENufy - esquema inicial Supabase
-- Execute este arquivo no SQL Editor do Supabase.

create extension if not exists "pgcrypto";

create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  logo_url text,
  cover_url text,
  phone text,
  whatsapp text not null,
  instagram text,
  address text,
  city text,
  state text,
  zip_code text,
  primary_color text default '#ff6b00',
  secondary_color text default '#18120e',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_members (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner' check (role in ('owner','manager','staff')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  promotional_price numeric(12,2),
  image_url text,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (promotional_price is null or promotional_price >= 0)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  order_number bigint generated by default as identity,
  status text not null default 'new'
    check (status in ('new','confirmed','preparing','out_for_delivery','completed','cancelled')),
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text not null check (payment_method in ('pix','cash','card')),
  order_type text not null check (order_type in ('delivery','pickup','local')),
  customer_name text not null,
  customer_phone text not null,
  delivery_address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null,
  quantity integer not null check (quantity > 0),
  subtotal numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_businesses_slug on public.businesses(slug);
create index if not exists idx_categories_business on public.categories(business_id);
create index if not exists idx_products_business on public.products(business_id);
create index if not exists idx_orders_business on public.orders(business_id);

alter table public.businesses enable row level security;
alter table public.business_members enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Leitura pública do cardápio.
create policy "public read active businesses"
on public.businesses for select
using (is_active = true);

create policy "public read active categories"
on public.categories for select
using (
  is_active = true and exists (
    select 1 from public.businesses b
    where b.id = categories.business_id and b.is_active = true
  )
);

create policy "public read active products"
on public.products for select
using (
  is_active = true and exists (
    select 1 from public.businesses b
    where b.id = products.business_id and b.is_active = true
  )
);

-- Dono/membro pode gerenciar sua empresa.
create policy "members read businesses"
on public.businesses for select
to authenticated
using (
  owner_id = auth.uid() or exists (
    select 1 from public.business_members bm
    where bm.business_id = businesses.id and bm.user_id = auth.uid()
  )
);

create policy "owner updates business"
on public.businesses for update
to authenticated
using (
  owner_id = auth.uid() or exists (
    select 1 from public.business_members bm
    where bm.business_id = businesses.id and bm.user_id = auth.uid()
  )
)
with check (
  owner_id = auth.uid() or exists (
    select 1 from public.business_members bm
    where bm.business_id = businesses.id and bm.user_id = auth.uid()
  )
);

create policy "owner inserts business"
on public.businesses for insert
to authenticated
with check (owner_id = auth.uid());

create policy "members read membership"
on public.business_members for select
to authenticated
using (user_id = auth.uid());

create policy "members manage categories"
on public.categories for all
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = categories.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = categories.business_id and b.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = categories.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = categories.business_id and b.owner_id = auth.uid()
  )
);

create policy "members manage products"
on public.products for all
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = products.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = products.business_id and b.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = products.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = products.business_id and b.owner_id = auth.uid()
  )
);

-- Checkout público: visitante pode criar pedido, mas não listar pedidos.
create policy "public create orders"
on public.orders for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.businesses b
    where b.id = orders.business_id and b.is_active = true
  )
);

create policy "business reads orders"
on public.orders for select
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = orders.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = orders.business_id and b.owner_id = auth.uid()
  )
);

create policy "business updates orders"
on public.orders for update
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = orders.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = orders.business_id and b.owner_id = auth.uid()
  )
);

create policy "public create order items"
on public.order_items for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.orders o
    join public.businesses b on b.id = o.business_id
    where o.id = order_items.order_id and b.is_active = true
  )
);

create policy "business reads order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    left join public.business_members bm
      on bm.business_id = o.business_id and bm.user_id = auth.uid()
    left join public.businesses b
      on b.id = o.business_id
    where o.id = order_items.order_id
      and (bm.user_id = auth.uid() or b.owner_id = auth.uid())
  )
);


-- Menufy — Supabase Realtime
-- Execute este arquivo depois de 001_initial_schema.sql.

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'businesses'
  ) then
    alter publication supabase_realtime add table public.businesses;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'categories'
  ) then
    alter publication supabase_realtime add table public.categories;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;

-- Garante payload completo em UPDATE/DELETE quando necessário.
alter table public.businesses replica identity full;
alter table public.categories replica identity full;
alter table public.products replica identity full;
alter table public.orders replica identity full;


-- Menufy - políticas para CRUD do painel administrativo

drop policy if exists "owners delete categories" on public.categories;
create policy "owners delete categories"
on public.categories for delete
to authenticated
using (
  exists (
    select 1 from public.businesses b
    where b.id = categories.business_id
      and b.owner_id = auth.uid()
  )
  or exists (
    select 1 from public.business_members bm
    where bm.business_id = categories.business_id
      and bm.user_id = auth.uid()
      and bm.role in ('owner','manager')
  )
);

drop policy if exists "owners delete products" on public.products;
create policy "owners delete products"
on public.products for delete
to authenticated
using (
  exists (
    select 1 from public.businesses b
    where b.id = products.business_id
      and b.owner_id = auth.uid()
  )
  or exists (
    select 1 from public.business_members bm
    where bm.business_id = products.business_id
      and bm.user_id = auth.uid()
      and bm.role in ('owner','manager')
  )
);

NOTIFY pgrst, 'reload schema';


NOTIFY pgrst, 'reload schema';
