-- MENufy - instalação completa

-- MENufy - esquema inicial Supabase
-- Execute este arquivo no SQL Editor do Supabase.

create extension if not exists "pgcrypto";

create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  logo_url text,
  cover_url text,
  phone text,
  whatsapp text not null,
  instagram text,
  address text,
  city text,
  state text,
  zip_code text,
  primary_color text default '#ff6b00',
  secondary_color text default '#18120e',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_members (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner' check (role in ('owner','manager','staff')),
  created_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  promotional_price numeric(12,2),
  image_url text,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (promotional_price is null or promotional_price >= 0)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  order_number bigint generated by default as identity,
  status text not null default 'new'
    check (status in ('new','confirmed','preparing','out_for_delivery','completed','cancelled')),
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text not null check (payment_method in ('pix','cash','card')),
  order_type text not null check (order_type in ('delivery','pickup','local')),
  customer_name text not null,
  customer_phone text not null,
  delivery_address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null,
  quantity integer not null check (quantity > 0),
  subtotal numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_businesses_slug on public.businesses(slug);
create index if not exists idx_categories_business on public.categories(business_id);
create index if not exists idx_products_business on public.products(business_id);
create index if not exists idx_orders_business on public.orders(business_id);

alter table public.businesses enable row level security;
alter table public.business_members enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Leitura pública do cardápio.
create policy "public read active businesses"
on public.businesses for select
using (is_active = true);

create policy "public read active categories"
on public.categories for select
using (
  is_active = true and exists (
    select 1 from public.businesses b
    where b.id = categories.business_id and b.is_active = true
  )
);

create policy "public read active products"
on public.products for select
using (
  is_active = true and exists (
    select 1 from public.businesses b
    where b.id = products.business_id and b.is_active = true
  )
);

-- Dono/membro pode gerenciar sua empresa.
create policy "members read businesses"
on public.businesses for select
to authenticated
using (
  owner_id = auth.uid() or exists (
    select 1 from public.business_members bm
    where bm.business_id = businesses.id and bm.user_id = auth.uid()
  )
);

create policy "owner updates business"
on public.businesses for update
to authenticated
using (
  owner_id = auth.uid() or exists (
    select 1 from public.business_members bm
    where bm.business_id = businesses.id and bm.user_id = auth.uid()
  )
)
with check (
  owner_id = auth.uid() or exists (
    select 1 from public.business_members bm
    where bm.business_id = businesses.id and bm.user_id = auth.uid()
  )
);

create policy "owner inserts business"
on public.businesses for insert
to authenticated
with check (owner_id = auth.uid());

create policy "members read membership"
on public.business_members for select
to authenticated
using (user_id = auth.uid());

create policy "members manage categories"
on public.categories for all
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = categories.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = categories.business_id and b.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = categories.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = categories.business_id and b.owner_id = auth.uid()
  )
);

create policy "members manage products"
on public.products for all
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = products.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = products.business_id and b.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = products.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = products.business_id and b.owner_id = auth.uid()
  )
);

-- Checkout público: visitante pode criar pedido, mas não listar pedidos.
create policy "public create orders"
on public.orders for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.businesses b
    where b.id = orders.business_id and b.is_active = true
  )
);

create policy "business reads orders"
on public.orders for select
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = orders.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = orders.business_id and b.owner_id = auth.uid()
  )
);

create policy "business updates orders"
on public.orders for update
to authenticated
using (
  exists (
    select 1 from public.business_members bm
    where bm.business_id = orders.business_id and bm.user_id = auth.uid()
  )
  or exists (
    select 1 from public.businesses b
    where b.id = orders.business_id and b.owner_id = auth.uid()
  )
);

create policy "public create order items"
on public.order_items for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.orders o
    join public.businesses b on b.id = o.business_id
    where o.id = order_items.order_id and b.is_active = true
  )
);

create policy "business reads order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    left join public.business_members bm
      on bm.business_id = o.business_id and bm.user_id = auth.uid()
    left join public.businesses b
      on b.id = o.business_id
    where o.id = order_items.order_id
      and (bm.user_id = auth.uid() or b.owner_id = auth.uid())
  )
);


-- Menufy — Supabase Realtime
-- Execute este arquivo depois de 001_initial_schema.sql.

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'businesses'
  ) then
    alter publication supabase_realtime add table public.businesses;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'categories'
  ) then
    alter publication supabase_realtime add table public.categories;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
end $$;

-- Garante payload completo em UPDATE/DELETE quando necessário.
alter table public.businesses replica identity full;
alter table public.categories replica identity full;
alter table public.products replica identity full;
alter table public.orders replica identity full;


-- Menufy - políticas para CRUD do painel administrativo

drop policy if exists "owners delete categories" on public.categories;
create policy "owners delete categories"
on public.categories for delete
to authenticated
using (
  exists (
    select 1 from public.businesses b
    where b.id = categories.business_id
      and b.owner_id = auth.uid()
  )
  or exists (
    select 1 from public.business_members bm
    where bm.business_id = categories.business_id
      and bm.user_id = auth.uid()
      and bm.role in ('owner','manager')
  )
);

drop policy if exists "owners delete products" on public.products;
create policy "owners delete products"
on public.products for delete
to authenticated
using (
  exists (
    select 1 from public.businesses b
    where b.id = products.business_id
      and b.owner_id = auth.uid()
  )
  or exists (
    select 1 from public.business_members bm
    where bm.business_id = products.business_id
      and bm.user_id = auth.uid()
      and bm.role in ('owner','manager')
  )
);

NOTIFY pgrst, 'reload schema';


NOTIFY pgrst, 'reload schema';


-- ============================================================
-- 004_dev_admin.sql
-- ============================================================

-- ============================================================
-- MENUFY - Admin Dev
-- Admin autorizado: rojonas71@gmail.com
-- ============================================================

create table if not exists public.dev_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.dev_admins enable row level security;

create or replace function public.is_dev_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dev_admins da
    where da.user_id = auth.uid()
  );
$$;

revoke all on function public.is_dev_admin() from public;
grant execute on function public.is_dev_admin() to authenticated;

drop policy if exists "dev_admin_read_own" on public.dev_admins;
create policy "dev_admin_read_own"
on public.dev_admins
for select
to authenticated
using (user_id = auth.uid());

-- Bootstrap do administrador já cadastrado no Auth.
insert into public.dev_admins (user_id, email)
select id, email
from auth.users
where lower(email) = lower('rojonas71@gmail.com')
on conflict (user_id) do update
set email = excluded.email;

-- Se o usuário ainda não existir no Auth quando esta migration for executada,
-- esta função garante o cadastro automático quando houver login/cadastro.
create or replace function public.sync_dev_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if lower(new.email) = lower('rojonas71@gmail.com') then
    insert into public.dev_admins (user_id, email)
    values (new.id, new.email)
    on conflict (user_id) do update
    set email = excluded.email;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_dev_admin on auth.users;
create trigger on_auth_user_dev_admin
after insert or update of email on auth.users
for each row
execute function public.sync_dev_admin();

-- ============================================================
-- Políticas globais do Admin Dev
-- ============================================================

drop policy if exists "dev_admin_all_businesses" on public.businesses;
create policy "dev_admin_all_businesses"
on public.businesses
for all
to authenticated
using (public.is_dev_admin())
with check (public.is_dev_admin());

drop policy if exists "dev_admin_all_business_members" on public.business_members;
create policy "dev_admin_all_business_members"
on public.business_members
for all
to authenticated
using (public.is_dev_admin())
with check (public.is_dev_admin());

drop policy if exists "dev_admin_all_categories" on public.categories;
create policy "dev_admin_all_categories"
on public.categories
for all
to authenticated
using (public.is_dev_admin())
with check (public.is_dev_admin());

drop policy if exists "dev_admin_all_products" on public.products;
create policy "dev_admin_all_products"
on public.products
for all
to authenticated
using (public.is_dev_admin())
with check (public.is_dev_admin());

drop policy if exists "dev_admin_all_orders" on public.orders;
create policy "dev_admin_all_orders"
on public.orders
for all
to authenticated
using (public.is_dev_admin())
with check (public.is_dev_admin());

drop policy if exists "dev_admin_all_order_items" on public.order_items;
create policy "dev_admin_all_order_items"
on public.order_items
for all
to authenticated
using (public.is_dev_admin())
with check (public.is_dev_admin());

notify pgrst, 'reload schema';


-- ============================================================
-- 005_business_plans.sql
-- ============================================================

-- ============================================================
-- MENUFY - Planos e assinatura do estabelecimento
-- ============================================================

alter table public.businesses
  add column if not exists plan text not null default 'starter',
  add column if not exists subscription_status text not null default 'active';

alter table public.businesses
  drop constraint if exists businesses_plan_check;

alter table public.businesses
  add constraint businesses_plan_check
  check (plan in ('starter', 'pro', 'premium'));

alter table public.businesses
  drop constraint if exists businesses_subscription_status_check;

alter table public.businesses
  add constraint businesses_subscription_status_check
  check (subscription_status in ('active', 'trial', 'past_due', 'cancelled'));

create index if not exists businesses_plan_idx
  on public.businesses(plan);

create index if not exists businesses_subscription_status_idx
  on public.businesses(subscription_status);

notify pgrst, 'reload schema';
